### PR TITLE
Fix document version at build time

### LINKED ISSUE #261: Incorrect information about the library
The library version is currently parsed from the manifest file in the 
`com.lowagie.text.VersionBean` class . If a program is built as a single jar file the manifest file of the library will be replaced and incorrect information will be parsed. This information is used by creation of pdf document (see: `com.lowagie.text.pdf.PdfPages` line: 152 / `com.lowagie.text.pdf.PdfStamperImp` line: 170. The constant `com.lowagie.text.pdf.PdfName.ITXT` is also no longer relevant).  It probably makes sense to store the library information in a property file or as constant values.

### PR DESCRIPTION
**Pull request by sixdouglas**
Set Document VERSION field with the current build version using properties file to fix #261 .

Remove VersionBean.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Why are you modifying FontTest in this pull request?

This pull request is of too poor quality, not ready for inclusion, and should be rejected.

**Comment by sixdouglas** [comment]
Hello
That’s true. This change shouldn’t have been there. 
I’be removed this change.

File: openpdf/src/main/java/com/lowagie/text/VersionBean.java [hunk 1]
```diff
@@ -53,7 +55,9 @@ void setManifest(Manifest manifest) {
      *
      * @author asmirnov@exadel.com (latest modification by $Author$)
      * @version $Revision$ $Date$
+     * @deprecated simce 1.3.11. Use Document.RELEASE
```
Comment (noavarice) [inline openpdf/src/main/java/com/lowagie/text/VersionBean.java]: Use `@Deprecated(since = "1.3.11", forRemoval =...)` instead of specifying version here (or in conjunction with, but then fix typo). And do the same with other added deprecations

File: openpdf/pom.xml [hunk 2]
```diff
@@ -58,8 +58,39 @@
             <resource>
                 <directory>src/main/resources-filtered</directory>
                 <filtering>true</filtering>
+                <includes>
+                    <include>**/version.txt</include>
+                    <include>**/version.properties</include>
+                </includes>
+            </resource>
+            <resource>
+                <directory>src/main/resources-filtered</directory>
```
Comment (noavarice) [inline openpdf/pom.xml]: Why these `<resource>` sections duplicated with just different `<filtering>` values?

File: openpdf/pom.xml [hunk 3]
```diff
@@ -58,8 +58,39 @@
             <resource>
                 <directory>src/main/resources-filtered</directory>
                 <filtering>true</filtering>
+                <includes>
+                    <include>**/version.txt</include>
```
Comment (noavarice) [inline openpdf/pom.xml]: If I understand your intention correctly, current OpenPDF version will be saved at specified files during build. If so, these files must be added to .gitignore. Or they will be generated not during compilation phase?

File: openpdf/src/test/java/com/lowagie/text/DocumentTest.java [hunk 4]
```diff
@@ -16,19 +16,22 @@ void testThatVersionIsCorrect() {
...
             String.format(ERROR_MESSAGE_TEMPLATE, versionInCode, versionFromPom));
     }
 
     private String getProjectVersion() {
-        InputStream is = this.getClass().getClassLoader().getResourceAsStream("version.txt");
+        InputStream is = this.getClass().getClassLoader().getResourceAsStream("com/lowagie/text/version.properties");
         String version = null;
         try (BufferedReader reader = new BufferedReader(new InputStreamReader(is))) {
             version = reader.readLine();
+            int eqPosition = version.indexOf('=');
```
Comment (noavarice) [inline openpdf/src/test/java/com/lowagie/text/DocumentTest.java]: Version is retrieved twice (at production and tests), but code is quite different. Consider using `Properties` here too

File: openpdf/src/main/java/com/lowagie/text/Document.java [hunk 5]
```diff
@@ -109,8 +112,24 @@
...
+    private static final String OPENPDF_VERSION;
+
+    static {
+        String releaseVersion = "";
+        try (InputStream input = Document.class.getClassLoader().getResourceAsStream("com/lowagie/text/version.properties")) {
+            Properties prop = new Properties();
+            // load a properties file
+            if (input != null) {
+                prop.load(input);
+                releaseVersion = prop.getProperty("bundleVersion", "");
```
Comment (noavarice) [inline openpdf/src/main/java/com/lowagie/text/Document.java]: `releaseVersion` variable is redundant, value can be assigned directly to `RELEASE`.

File: openpdf/src/main/java/com/lowagie/text/Document.java [hunk 6]
```diff
@@ -109,8 +112,24 @@
...
+            }
+        } catch (IOException ex) {
+            ex.printStackTrace();
```
Comment (noavarice) [inline openpdf/src/main/java/com/lowagie/text/Document.java]: I guess that failure of version retrieval is not a situation that can be handled, so just rethrow, for example, `IllegalStateException` or even maybe some kind of `Error`
